package com.aire.ui.theme

import androidx.compose.ui.graphics.Color

val SeafoamTeal = Color(0xFF1B6C78)
val SeafoamTealLight = Color(0xFFE0F2F1)
val HoneyAmber = Color(0xFFFFB300)
val SoftRose = Color(0xFF904A42)

val md_theme_light_primary = SeafoamTeal
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFADECEF)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = HoneyAmber
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE082)
val md_theme_light_onSecondaryContainer = Color(0xFF241A00)
val md_theme_light_tertiary = SoftRose
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onTertiaryContainer = Color(0xFF3B0907)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF4FBFA)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFF4FBFA)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE4E4)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4ED8E8)
val md_theme_light_surfaceTint = Color(0xFF006972)
val md_theme_light_outlineVariant = Color(0xFFBEC8C8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4ED8E8)
val md_theme_dark_onPrimary = Color(0xFF00363C)
val md_theme_dark_primaryContainer = Color(0xFF004F56)
val md_theme_dark_onPrimaryContainer = Color(0xFFADECEF)
val md_theme_dark_secondary = Color(0xFFFFC107)
val md_theme_dark_onSecondary = Color(0xFF402D00)
val md_theme_dark_secondaryContainer = Color(0xFF5C4300)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE082)
val md_theme_dark_tertiary = Color(0xFFFFB4AB)
val md_theme_dark_onTertiary = Color(0xFF561D19)
val md_theme_dark_tertiaryContainer = Color(0xFF73332D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val md_theme_dark_outline = Color(0xFF899392)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inversePrimary = Color(0xFF006972)
val md_theme_dark_surfaceTint = Color(0xFF4ED8E8)
val md_theme_dark_outlineVariant = Color(0xFF3F4948)
val md_theme_dark_scrim = Color(0xFF000000)
